version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "org.glassfish.jaxb:jaxb-runtime"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.apache.kafka:kafka_2.12"
        update-types: ["version-update:semver-major"]
      - dependency-name: "com.sun.xml.ws:jaxws-tools"
        update-types: ["version-update:semver-major"]
      - dependency-name: "redis.clients:jedis"
        update-types: ["version-update:semver-major"]
             
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
