apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: syfosminfotrygd
  namespace: default
  labels:
    team: "teamsykefravr"
spec:
  name: "syfosminfotrygd"
  image: "repo.adeo.no:5443/syfo/syfosminfotrygd:@@VERSION@@"
  replicas:
    min: 1
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 5
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /is_ready
    initialDelay: 5
    timeout: 1
    periodSeconds: 10
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
  env:
    - name: PERSON_V3_ENDPOINT_URL
      value: {{PERSON_V3_ENDPOINT_URL}}
    - name: SECURITY_TOKEN_SERVICE_URL
      value: {{SECURITY_TOKEN_SERVICE_URL}}
    - name: INFOTRYGD_SPORRING_QUEUE
      value: {{INFOTRYGD_SPORRING_QUEUE}}
    - name: INFOTRYGD_OPPDATERING_QUEUE
      value: {{INFOTRYGD_OPPDATERING_QUEUE}}
    - name: ORGANISASJONENHET_V2_ENDPOINT_URL
      value: {{ORGANISASJONENHET_V2_ENDPOINT_URL}}
    - name: MQ_HOST_NAME
      value: {{MQ_HOST_NAME}}
    - name: MQ_PORT
      value: '{{MQ_PORT}}'
    - name: MQ_GATEWAY_NAME
      value: {{MQ_GATEWAY_NAME}}
    - name: MQ_CHANNEL_NAME
      value: {{MQ_CHANNEL_NAME}}
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: {{KAFKA_BOOTSTRAP_SERVERS_URL}}
    - name: HELSEPERSONELL_V1_ENDPOINT_URL
      value: {{HELSEPERSONELL_V1_ENDPOINT_URL}}