apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosminfotrygd
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 6
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 900Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: syfosmmanuell-backend
        - application: syfosmregister
        - application: flex-syketilfelle
          namespace: flex
          cluster: prod-gcp
        - application: syfohelsenettproxy
        - application: norg2
          namespace: org
          cluster: prod-gcp
      external:
        - host: pdl-api.prod-fss-pub.nais.io
        - host: norg2.prod-fss-pub.nais.io
        - host: mpls03.adeo.no
          ports:
            - port: 1414
    inbound:
      rules:
        - application: macgyver
  kafka:
    pool: nav-prod
  valkey:
    - instance: infotrygd
      access: readwrite
  envFrom:
    - secret: syfosminfotrygd-secrets
  env:
    - name: INFOTRYGD_SPORRING_QUEUE
      value: QA.P278.IT00_FORESPORSEL_XML
    - name: INFOTRYGD_OPPDATERING_QUEUE
      value: QA.P278.IT00_SMOPPDATERING
    - name: MQ_HOST_NAME
      value: mpls03.adeo.no
    - name: MQ_PORT
      value: '1414'
    - name: MQ_GATEWAY_NAME
      value: MPLS03
    - name: MQ_CHANNEL_NAME
      value: P_SYFOSMINFOTRYGD
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: HELSENETT_SCOPE
      value: api://prod-gcp.teamsykmelding.syfohelsenettproxy/.default
    - name: MANUELL_SCOPE
      value: api://prod-gcp.teamsykmelding.syfosmmanuell-backend/.default
    - name: SYKETILLFELLE_SCOPE
      value: api://prod-gcp.flex.flex-syketilfelle/.default
    - name: SMREGISTER_AUDIENCE
      value: api://prod-gcp.teamsykmelding.syfosmregister/.default
