apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosminfotrygd
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  kafka:
    pool: nav-dev
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvsyfosminfotrygd
        mountPath: /secrets/serviceuser
      - kvPath: /kv/preprod/fss/syfosminfotrygd/teamsykmelding
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  envFrom:
    - secret: syfosminfotrygd-redis-password
  env:
    - name: INFOTRYGD_SPORRING_QUEUE
      value: QA.Q291.IT00_FORESPORSEL_XML
    - name: INFOTRYGD_OPPDATERING_QUEUE
      value: QA.Q291.IT00_SMOPPDATERING
    - name: MQ_HOST_NAME
      value: b27apvl173.preprod.local
    - name: MQ_PORT
      value: '1413'
    - name: MQ_GATEWAY_NAME
      value: MQ1LSC03
    - name: MQ_CHANNEL_NAME
      value: Q1_SYFOSMINFOTRYGD
    - name: NORG2_V1_ENDPOINT_URL
      value: https://norg2.dev.adeo.no/norg2/api/v1
    - name: MQ_TSS_SAMHANDLER_SERVICE_QUEUE
      value: QA.Q1_415.AS10_SAMHANDLER_SERVICE
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.preprod.local/graphql
    - name: HELSENETT_ENDPOINT_URL
      value: https://syfohelsenettproxy.nais.preprod.local
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: HELSENETT_SCOPE
      value: api://dev-fss.teamsykmelding.syfohelsenettproxy/.default
    - name: MANUELL_SCOPE
      value: api://dev-fss.teamsykmelding.syfosmmanuell-backend/.default