apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosminfotrygd
  namespace: default
  labels:
    team: {{team}}
spec:
  image: "docker.pkg.github.com/navikt/syfosminfotrygd:{{tag}}"
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
  webproxy: true
  env:
    - name: PERSON_V3_ENDPOINT_URL
      value: https://wasapp-q1.adeo.no/tpsws/ws/Person/v3
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    - name: INFOTRYGD_SPORRING_QUEUE
      value: QA.Q291.IT00_FORESPORSEL_XML
    - name: INFOTRYGD_OPPDATERING_QUEUE
      value: QA.Q291.IT00_SMOPPDATERING
    - name: ARBEIDSFORDELING_V1_ENDPOINT_URL
      value: https://app-q1.adeo.no/norg2/ws/Arbeidsfordeling/v1
    - name: MQ_HOST_NAME
      value: b27apvl173.preprod.local
    - name: MQ_PORT
      value: '1413'
    - name: MQ_GATEWAY_NAME
      value: MQ1LSC03
    - name: MQ_CHANNEL_NAME
      value: Q1_SYFOSMINFOTRYGD
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: HELSEPERSONELL_V1_ENDPOINT_URL
      value: https://pep-gw-q1.oera-q.local:9443/samhandler/helse/helsepersonell/v1
    - name: MQ_INFOTRYGD_SMIKKEOK_QUEUE
      value: Q414.AS07_SMIKKEOK
    - name: NORG2_V1_ENDPOINT_URL
      value: https://app-q1.adeo.no/norg2/api/v1
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/token
    - name: CLIENT_ID
      value: b5f266e7-cf26-4688-abc3-f44d78f5702c
    - name: HELSENETTPROXY_ID
      value: c18eba24-f676-47db-9a97-3c66e9304aee