apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosminfotrygd
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    outbound:
      rules:
        - application: syfosmmanuell-backend
        - application: syfosmregister
        - application: flex-syketilfelle
          namespace: flex
          cluster: dev-gcp
        - application: syfohelsenettproxy
        - application: norg2
          namespace: org
          cluster: dev-gcp
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: norg2.dev-fss-pub.nais.io
        - host: b27apvl221.preprod.local
          ports:
            - port: 1413
    inbound:
      rules:
        - application: macgyver
          namespace: teamsykmelding
          cluster: dev-gcp
  kafka:
    pool: nav-dev
  valkey:
    - instance: infotrygd
      access: readwrite
  envFrom:
    - secret: syfosminfotrygd-secrets
  secureLogs:
    enabled: true
  env:
    - name: INFOTRYGD_SPORRING_QUEUE
      value: QA.Q291.IT00_FORESPORSEL_XML
    - name: INFOTRYGD_OPPDATERING_QUEUE
      value: QA.Q291.IT00_SMOPPDATERING
    - name: MQ_HOST_NAME
      value: b27apvl221.preprod.local
    - name: MQ_PORT
      value: '1413'
    - name: MQ_GATEWAY_NAME
      value: MQLS03
    - name: MQ_CHANNEL_NAME
      value: Q1_SYFOSMINFOTRYGD
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: HELSENETT_SCOPE
      value: api://dev-gcp.teamsykmelding.syfohelsenettproxy/.default
    - name: MANUELL_SCOPE
      value: api://dev-gcp.teamsykmelding.syfosmmanuell-backend/.default
    - name: SYKETILLFELLE_SCOPE
      value: api://dev-gcp.flex.flex-syketilfelle/.default
    - name: SMREGISTER_AUDIENCE
      value: api://dev-gcp.teamsykmelding.syfosmregister/.default
