apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosminfotrygd
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvsyfosminfotrygd
        mountPath: /secrets/serviceuser
      - kvPath: /kv/prod/fss/syfosminfotrygd/teamsykmelding
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  envFrom:
    - secret: syfosminfotrygd-redis-password
  env:
    - name: INFOTRYGD_SPORRING_QUEUE
      value: QA.P278.IT00_FORESPORSEL_XML
    - name: INFOTRYGD_OPPDATERING_QUEUE
      value: QA.P278.IT00_SMOPPDATERING
    - name: MQ_HOST_NAME
      value: a01apvl270.adeo.no
    - name: MQ_PORT
      value: '1414'
    - name: MQ_GATEWAY_NAME
      value: MPLS03
    - name: MQ_CHANNEL_NAME
      value: P_SYFOSMINFOTRYGD
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443
    - name: MQ_INFOTRYGD_SMIKKEOK_QUEUE
      value: P414.AS07_SMIKKEOK
    - name: NORG2_V1_ENDPOINT_URL
      value: https://norg2.nais.adeo.no/norg2/api/v1
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/token
    - name: CLIENT_ID
      value: 2c9d40f1-81c2-4f8d-b862-aabd14ab901c
    - name: HELSENETTPROXY_ID
      value: b813133d-82b8-46ef-be96-3b903ea6c048
    - name: MQ_TSS_SAMHANDLER_SERVICE_QUEUE
      value: QA.P415.AS10_SAMHANDLER_SERVICE
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.adeo.no/graphql
    - name: HELSENETT_ENDPOINT_URL
      value: https://syfohelsenettproxy.nais.adeo.no
